### ISSUE TITLE
Status updates when there is no manifest

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/seaeye#1]
At the moment we get a green tick in the "no manifest case".

It might be better if seaeye avoided sending status updates until it saw the manifest. A green tick feels deceptive, since in fact tests haven't run.

Just a suggestion and I'm willing to debate it.

**Comment by djui** [comment]
I was a bit uncertain about this as you can see in the code [L127-L131](https://github.com/scraperwiki/seaeye/blob/master/pkg/seaeye/job.go#L127-L131).

A consequences of this requests would be that no other `pending` messages are send before that, eg. `Stage Fetching started` [L102](https://github.com/scraperwiki/seaeye/blob/master/pkg/seaeye/job.go#L102). But I guess it's better to not report any fake successes.

**Comment by djui** [comment]
Fixed by https://github.com/scraperwiki/seaeye/commit/f0ed0852d10c9c09ec93d131398657135dd0b5d9.
