### ISSUE TITLE
<br> tags are encoded in log viewer

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/seaeye#2]
It looks like this:

![screenshot from 2016-06-03 11-48-24](https://cloud.githubusercontent.com/assets/438648/15776643/1cc2b100-2981-11e6-9605-8cd586bc5444.png)
![screenshot from 2016-06-03 11-48-16](https://cloud.githubusercontent.com/assets/438648/15776644/1cd864d2-2981-11e6-8516-7da9ff22ce17.png)

**Comment by djui** [comment]
Fixed by https://github.com/scraperwiki/seaeye/commit/a11148927ddf2cedce38105925e2ba83452531a0.
